### ISSUE TITLE
Сервер не 24/7

### ISSUE THREAD

**Issue by skat-spec** [getdrive/vps#1]
Выключается когда я больше 1 часа не захожу в браузер

**Comment by skat-spec** [comment]
Мне например нужно, чтобы он не выключался, а то снова запускать лень + неудобно, тем более я искал 24/7 для игр

**Comment by getdrive** [comment]
Заголовок файла  README.md гласит: "Free RDP 6 HOURS"
А если учесть, что тема халявы набрала тренд, то возможно уже и меньше - не проверял.
